// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_TuD7sS9yjLr2kIc0rikMNt_8qYtcec',
    appId: '1:832591828608:web:9204677efd3adc47803865',
    messagingSenderId: '832591828608',
    projectId: 'dogal-afetler',
    authDomain: 'dogal-afetler.firebaseapp.com',
    databaseURL: 'https://dogal-afetler-default-rtdb.firebaseio.com',
    storageBucket: 'dogal-afetler.appspot.com',
    measurementId: 'G-XXL6862N4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiejNSl160lwtQi3H6cYfMjVCu_x8haj4',
    appId: '1:832591828608:android:7e73b18df94a5005803865',
    messagingSenderId: '832591828608',
    projectId: 'dogal-afetler',
    databaseURL: 'https://dogal-afetler-default-rtdb.firebaseio.com',
    storageBucket: 'dogal-afetler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQNQz_HBsIGU6T_GZwKHepEg70j4lLG8',
    appId: '1:832591828608:ios:036652e027e9dd19803865',
    messagingSenderId: '832591828608',
    projectId: 'dogal-afetler',
    databaseURL: 'https://dogal-afetler-default-rtdb.firebaseio.com',
    storageBucket: 'dogal-afetler.appspot.com',
    iosClientId: '832591828608-qvm98v0rkh0l1q8i03e02g0aj3rgv17p.apps.googleusercontent.com',
    iosBundleId: 'com.example.hikod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQNQz_HBsIGU6T_GZwKHepEg70j4lLG8',
    appId: '1:832591828608:ios:036652e027e9dd19803865',
    messagingSenderId: '832591828608',
    projectId: 'dogal-afetler',
    databaseURL: 'https://dogal-afetler-default-rtdb.firebaseio.com',
    storageBucket: 'dogal-afetler.appspot.com',
    iosClientId: '832591828608-qvm98v0rkh0l1q8i03e02g0aj3rgv17p.apps.googleusercontent.com',
    iosBundleId: 'com.example.hikod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_TuD7sS9yjLr2kIc0rikMNt_8qYtcec',
    appId: '1:832591828608:web:a9b4b9921a371fb9803865',
    messagingSenderId: '832591828608',
    projectId: 'dogal-afetler',
    authDomain: 'dogal-afetler.firebaseapp.com',
    databaseURL: 'https://dogal-afetler-default-rtdb.firebaseio.com',
    storageBucket: 'dogal-afetler.appspot.com',
    measurementId: 'G-CYD2KLV6M9',
  );

}